<script src="/js/jquery-1.10.2.min.js"></script>
<script src='/js/bootstrapvalidator.min.js'></script>
<script src="/js/jquery.min.js"></script>
<script src="/bootstrap/js/jquery-ui.min.js"></script>
<script src="/bootstrap/js/bootstrap.min.js"></script>
<script src="/bootstrap/js/validator.js"></script>
<!-- <script src="/plugins/knob/jquery.knob.js"></script> -->
<!-- <script src="/bootstrap/js/moment.min.js"></script> -->
<script src="/plugins/fileinput/fileinput.js"></script>
<script src="/plugins/fileinput/fileinput.min.js"></script>
<script src="/plugins/fileinput/explorer/theme.js"></script>
<!-- <script src="/plugins/fileinput/sortable.js"></script> -->
<script src="/locales/fr.js"></script>
<script src="/locales/es.js"></script>
<script src="/plugins/daterangepicker/daterangepicker.js"></script>
<script src="/plugins/datepicker/bootstrap-datepicker.js"></script>
<script src="/plugins/iCheck/icheck.min.js"></script>
<script src="/plugins/slimScroll/jquery.slimscroll.min.js"></script>
<script src="/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="/plugins/input-mask/jquery.inputmask.js"></script>
<script src="/plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
<script src="/plugins/input-mask/jquery.inputmask.extensions.js"></script>
<script src="/plugins/fastclick/fastclick.js"></script>
<script src="/plugins/select2/select2.full.min.js"></script>
<script src="/js/noty/packaged/jquery.noty.packaged.min.js"></script>
<script src="/dist/js/app.min.js"></script>
<script src="/plugins/timepicker/bootstrap-timepicker.min.js"></script>
<script src="/plugins/datepicker/bootstrap-datepicker.min.js"></script>
